asset/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from hnf import views

urlpatterns = [
    # 无论访问那个页面都会跳转到登陆页面
    url(r'^$', views.login),
    # 登陆
    url(r'^login', views.login),
    # 注销
    url(r'^logout', views.logout),
    # 搜索
    url(r'^search', views.search, name='search'),
    # django自带后台
    url(r'^admin/', admin.site.urls),
    # 展示页面
    url(r'^asset/list/$', views.asset_list, name='asset_list'),
    url(r'^asset/add/$', views.asset_add),
    url(r'^asset/edit/(?P<cid>\d+)/$', views.asset_edit),
    url(r'^asset/del/(?P<cid>\d+)/$', views.asset_del),
    # 导入
    url(r'^asset/import/$', views.asset_import),
    # 导入模板
    url(r'^asset/tpl/$', views.asset_tpl),

]

hnf/urls.py
from django.conf.urls import url
# from hnf.views import userinfo
# urlpatterns=[
#     url(r'^user/list/$',userinfo.user_list),
#     url(r'^user/add/$',userinfo.user_add),
#     url(r'^user/edit/$',userinfo.user_edit),
#     url(r'^user/add/$',userinfo.user_del),

# ]

hnf/utils/urls.py
from django.urls import reverse


def memory_reverse(request, name, *args, **kwargs):
    """
    反向生成带条件的URL
    :param request:  传这个参数是获取url后面携带的参数
    :param name:  这个是views里面url的别名
    :param args:
    :param kwargs:
    :return:
    """

    url = reverse(name, args=args, kwargs=kwargs)
    filter = request.GET.get('_filter')
    if not filter:
        return url
    return "%s?%s" % (url, filter,)

hnf/models.py
# -*- coding: utf-8 -*-
from django.db import models


# Create your models here.

class Userinfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)
    department = models.CharField(verbose_name='部门', max_length=32)

    def __str__(self):
        return self.username
    class Meta:
        verbose_name = "用户表"
        verbose_name_plural = verbose_name



class Asset(models.Model):
    """
    资产表
    """
    brand = models.CharField(verbose_name='品牌', max_length=32)
    model = models.CharField(verbose_name='型号', max_length=32)
    number = models.CharField(verbose_name='编号', max_length=32)
    leader_time = models.DateTimeField(verbose_name='领用时间', max_length=32)
    leader = models.CharField(verbose_name='领用人', max_length=32)
    return_time = models.DateTimeField(verbose_name='归还时间', max_length=32,null=True)
    other = models.CharField(verbose_name='备注', max_length=128,null=True)

    def __str__(self):

        return self.leader

    class Meta:
        verbose_name="资产表"
        verbose_name_plural = verbose_name

hnf/forms/asset.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.forms import ModelForm, Form
from django import forms
from hnf import models


class AssetForm(ModelForm):
    class Meta:
        model = models.Asset
        fields = "__all__"

    def __init__(self, *args, **kwargs):

        super(AssetForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control' # 应用样式
            # field.widget.attrs['id'] = 'time' # 应用样式
            field.widget.attrs['placeholder'] = field.label #默认显示的字段
        # self.fields['brand'].empty_label = "请选择品牌"
        self.fields['other'].required = False
        self.fields['return_time'].required = False



class PaymentUserForm(ModelForm):
    class Meta:
        model = models.Asset
        exclude = ['customer',]

    def __init__(self, *args, **kwargs):
        super(PaymentUserForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

hnf/forms/customer.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.forms import ModelForm, Form
from hnf import models
from django import forms


class UserinfoForm(ModelForm):
    class Meta:
        model = models.Userinfo
        fields = "__all__"
        widgets = {
            "password": forms.widgets.PasswordInput(attrs={"class": "form-control"}),
    }

    def __init__(self, *args, **kwargs):
        super(UserinfoForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

hnf/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
import os
import mimetypes
from django.shortcuts import render, redirect
from django.http import FileResponse
from django.conf import settings
import xlrd
from asset import mypage
from hnf.forms.customer import UserinfoForm
from hnf.forms.asset import AssetForm
from hnf import models

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from hnf.utils.urls import memory_reverse


# Create your views here.
# 登录页面
def login(request):
    if request.method == "GET":
        return render(request, "login.html")
    else:
        next_url = request.GET.get("next")

        username = request.POST.get("username")
        pwd = request.POST.get("password")
        user_obj = auth.authenticate(request, username=username, password=pwd)
        if user_obj:
            auth.login(request, user_obj)  # # 给该次请求设置了session数据，并在响应中回写cookie
            if next_url:
                return redirect(next_url)
            else:
                return redirect("/asset/list/")
        else:
            return render(request, "login.html", {"error_msg": "用户名或密码错误"})


# 注销页面
def logout(request):
    auth.logout(request)
    return redirect("/login/")


def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'result.html', {'error_msg': error_msg})

    # post_list = models.Asset.objects.filter(leader__icontains=q)
    # for i in post_list:
    data_list = models.Asset.objects.filter(leader__contains=q)
    return render(request, 'result.html', {'error_msg': error_msg, 'post_list': data_list})


def user_list(request):
    """
    用户列表
    :return:
    """
    data_list = models.Userinfo.objects.all()

    return render(request, 'user_list.html', {'data_list': data_list})


def user_add(request):
    """
    添加用户
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = UserinfoForm()
        return render(request, 'user_add.html', {'form': form})
    form = UserinfoForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')
    return render(request, 'user_add.html', {'form': form})


def user_edit(request, cid):
    """
    编辑客户
    :return:
    """
    obj = models.Userinfo.objects.get(id=cid)
    if request.method == 'GET':
        form = UserinfoForm(instance=obj)
        return render(request, 'user_edit.html', {'form': form})
    form = UserinfoForm(data=request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')
    return render(request, 'user_edit.html', {'form': form})


def user_del(request, cid):
    """
    删除客户
    :param request:
    :param cid:
    :return:
    """
    models.Userinfo.objects.filter(id=cid).delete()
    return redirect('/user/list/')


def user_import(request):
    """
    批量导入用户
    :param request:
    :return:
    """

    if request.method == 'GET':
        return render(request, 'user_import.html')

    context = {'status': True, 'msg': '导入成功'}
    try:
        customer_excel = request.FILES.get('customer_excel')
        """
        打开上传的Excel文件，并读取内容
        注：打开本地文件时，可以使用：workbook = xlrd.open_workbook(filename='本地文件路径.xlsx')
        """
        workbook = xlrd.open_workbook(file_contents=customer_excel.file.read())

        # sheet = workbook.sheet_by_name('工作表1')
        sheet = workbook.sheet_by_index(0)
        row_map = {
            0: {'text': '用户名', 'name': 'username'},
            1: {'text': '密码', 'name': 'password'},
            2: {'text': '部门', 'name': 'department'},

        }
        object_list = []
        for row_num in range(1, sheet.nrows):
            row = sheet.row(row_num)
            print(row)
            row_dict = {}
            for col_num, name_text in row_map.items():
                row_dict[name_text['name']] = row[col_num].value
            object_list.append(models.Userinfo(**row_dict))

        models.Userinfo.objects.bulk_create(object_list, batch_size=20)
    except Exception as e:
        context['status'] = False
        context['msg'] = '导入失败'

    return render(request, 'user_import.html', context)


def user_tpl(request):
    """
    下载批量导入Excel列表
    :param request:
    :return:
    """
    tpl_path = os.path.join(settings.BASE_DIR, 'hnf', 'files', '批量导入用户模板.xlsx')
    content_type = mimetypes.guess_type(tpl_path)[0]
    print(content_type)
    response = FileResponse(open(tpl_path, mode='rb'), content_type=content_type)
    response['Content-Disposition'] = "attachment;filename=%s" % 'user_excel_tpl.xlsx'
    return response


@login_required()
def asset_list(request):
    """
    资产列表
    :return:
    """
    data_list = models.Asset.objects.all()
    print(data_list)
    total_count = data_list.count()

    current_page = request.GET.get("page")

    page_boj = mypage.MyPage(current_page, total_count, url_prefix="asset/list")
    data = data_list[:]  # 从第几页显示到第几页

    page_html = page_boj.page_html()  # 页面
    page_num = page_boj.num()  # 序号

    return render(request, 'asset_list.html', {'data_list': data, 'page_html': page_html, 'num': page_num})


def asset_add(request):
    """
    添加资产
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = AssetForm()
        return render(request, 'asset_add.html', {'form': form})
    form = AssetForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/asset/list/')
    return render(request, 'asset_add.html', {'form': form})


def asset_edit(request, cid):
    """
    编辑资产
    :return:
    """
    obj = models.Asset.objects.get(id=cid)
    if request.method == 'GET':
        form = AssetForm(instance=obj)
        return render(request, 'asset_edit.html', {'form': form})
    form = AssetForm(data=request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('/asset/list/')
    return render(request, 'asset_edit.html', {'form': form})


def asset_del(request, cid):
    """
    删除资产
    :param request:
    :param cid:
    :return:
    """
    # models.Asset.objects.filter(id=cid).delete()
    #
    # return redirect('/asset/list/')

    origin = memory_reverse(request, 'asset_list')
    print(origin)
    if request.method == 'GET':
        return render(request, 'delete.html', {'cancel': origin})
    models.Asset.objects.filter(id=cid).delete()
    return redirect(origin)


def asset_import(request):
    """
    批量导入
    :param request:
    :return:
    """

    if request.method == 'GET':
        return render(request, 'asset_import.html')

    context = {'status': True, 'msg': '导入成功'}
    try:
        customer_excel = request.FILES.get('customer_excel')
        """
        打开上传的Excel文件，并读取内容
        注：打开本地文件时，可以使用：workbook = xlrd.open_workbook(filename='本地文件路径.xlsx')
        """
        workbook = xlrd.open_workbook(file_contents=customer_excel.file.read())

        # sheet = workbook.sheet_by_name('工作表1')
        sheet = workbook.sheet_by_index(0)
        row_map = {
            0: {'text': '品牌', 'name': 'brand'},
            1: {'text': '型号', 'name': 'model'},
            2: {'text': '编号', 'name': 'number'},
            3: {'text': '领用时间', 'name': 'leader_time'},
            4: {'text': '领用人', 'name': 'leader'},
            5: {'text': '归还时间', 'name': 'return_time'},
            6: {'text': '备注', 'name': 'other'},

        }
        object_list = []
        for row_num in range(1, sheet.nrows):
            row = sheet.row(row_num)
            print(row)
            row_dict = {}
            for col_num, name_text in row_map.items():
                row_dict[name_text['name']] = row[col_num].value
            object_list.append(models.Asset(**row_dict))

        models.Asset.objects.bulk_create(object_list, batch_size=20)
    except Exception as e:
        context['status'] = False
        context['msg'] = '导入失败'

    return render(request, 'asset_import.html', context)


def asset_tpl(request):
    """
    下载批量导入Excel列表
    :param request:
    :return:
    """
    tpl_path = os.path.join(settings.BASE_DIR, 'hnf', 'files', '批量导入商品模板.xlsx')
    content_type = mimetypes.guess_type(tpl_path)[0]
    print(content_type)
    response = FileResponse(open(tpl_path, mode='rb'), content_type=content_type)
    response['Content-Disposition'] = "attachment;filename=%s" % 'asset_excel_tpl.xlsx'
    return response

hnf/templates/asset_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group col-sm-6 clearfix">
                    <label class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }} <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/laydate/laydate.js"></script>

<script>
//执行一个laydate实例
laydate.render({
  elem: '#id_leader_time'

});
</script>

<script>
//执行一个laydate实例
laydate.render({
  elem: '#id_return_time'

});
</script>
{% endblock %}

hnf/templates/asset_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group col-sm-6 clearfix">
                    <label class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }} <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/laydate/laydate.js"></script>

<script>
//执行一个laydate实例
laydate.render({
  elem: '#id_leader_time'

});
</script>

<script>
//执行一个laydate实例
laydate.render({
  elem: '#id_return_time'

});
</script>
{% endblock %}

hnf/templates/asset_import.html
{% extends 'layout.html' %}

{% block content %}

    <div class="luffy-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <div
                        style="position: relative;display: inline-block;height: 50px;min-width: 300px;overflow: hidden;">
                    <div style="position: absolute;top: 0;left: 0;right: 0;bottom: 0;z-index: 1000;border: 1px dotted #9d9d9d;color: #9d9d9d;line-height: 50px;padding-left: 15px;">
                        <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                        <span>点击上传Excel文件</span>
                    </div>
                    <input name="customer_excel" type="file" id="excelFile"
                           style="position: absolute;top: 0;left: 0;right: 0;bottom: 0;background-color: #333333;z-index: 1001;opacity: 0;filter:alpha(opacity=0);">
                </div>
                <p class="help-block">注意：批量导入的Excel需使用规定格式模板. <a href="/asset/tpl/">下载模板</a></p>
            </div>
            <button type="submit" class="btn btn-primary">上传</button>
            {% if status %}
                <span style="color: green;">{{ msg }}</span>
            {% else %}
                <span style="color: red;">{{ msg }}</span>
            {% endif %}
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('#excelFile').change(function (e) {
                var fileName = e.currentTarget.files[0].name;
                $(this).prev().find('span').text(fileName);
            })
        })
    </script>
{% endblock %}

hnf/templates/asset_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
            <a class="btn btn-default" href="/asset/add/">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 商品入库
            </a>
            <a class="btn btn-default" href="/asset/import/">
                <i class="fa fa-file-excel-o" aria-hidden="true"></i> 批量导入商品
            </a>
            <div class="right" style="margin-left: 911px" >
                <form method="get" action="{% url 'search' %}">
                    {#{% csrf_token %}#}
                  <input name="q"  type="search" placeholder="请输入商品名" required>
                  <button type="submit">搜索</button>
                </form>

            </div>

        </div>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>商品名</th>
                <th>型号</th>
                <th>编号</th>
                <th>入库时间</th>
                <th>领用人</th>
                <th>出库时间</th>
                <th>备注</th>
                <th>编辑</th>

            </tr>
            </thead>
            <tbody>
            {% for row in data_list %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.brand }}</td>
                    <td>{{ row.model }}</td>
                    <td>{{ row.number }}</td>
                    <td>{{ row.leader_time|date:"Y-m-d" }}</td>
                    <td>{{ row.leader }}</td>
                    <td>{{ row.return_time|date:"Y-m-d" }}</td>
                    <td>{{ row.other }}</td>

                    <td>
                        <a style="color: #333333;" href="/asset/edit/{{ row.id }}/">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        |
                        <a style="color: #d9534f;" href="/asset/del/{{ row.id }}/"><i class="fa fa-trash-o"></i></a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    {{ page_html|safe }}
    </div>
{% endblock %}

hnf/templates/delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i> 删除后将不可恢复，请确定是否删除？</p>
                <div style="margin-top: 20px;">
                    <a href="{{ cancel }}" class="btn btn-default btn-sm">取消</a>
                    <button type="submit" class="btn btn-danger btn-sm">确 认</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

hnf/templates/layout.html
<!--<!DOCTYPE html>-->
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>路飞学城</title>
    <link rel="shortcut icon" href="{% static 'imgs/luffy-study-logo.png' %} ">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %} "/>
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/commons.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/nav.css' %} "/>
    <style>
        body {
            margin: 0;
        }

        .no-radius {
            border-radius: 0;
        }

        .no-margin {
            margin: 0;
        }

        .pg-body > .left-menu {
            background-color: #EAEDF1;
            position: absolute;
            left: 1px;
            top: 48px;
            bottom: 0;
            width: 220px;
            border: 1px solid #EAEDF1;
            overflow: auto;
        }

        .pg-body > .right-body {
            position: absolute;
            left: 225px;
            right: 0;
            top: 48px;
            bottom: 0;
            overflow: scroll;
            border: 1px solid #ddd;
            border-top: 0;
            font-size: 13px;
            min-width: 755px;
        }

        .navbar-right {
            float: right !important;
            margin-right: -15px;
        }

        .luffy-container {
            padding: 15px;
        }

        .left-menu .menu-body .static-menu {

        }

        .left-menu .menu-body .static-menu .icon-wrap {
            width: 20px;
            display: inline-block;
            text-align: center;
        }

        .left-menu .menu-body .static-menu a {
            text-decoration: none;
            padding: 8px 15px;
            border-bottom: 1px solid #ccc;
            color: #333;
            display: block;
            background: #efefef;
            background: -webkit-gradient(linear, left bottom, left top, color-stop(0, #efefef), color-stop(1, #fafafa));
            background: -ms-linear-gradient(bottom, #efefef, #fafafa);
            background: -moz-linear-gradient(center bottom, #efefef 0%, #fafafa 100%);
            background: -o-linear-gradient(bottom, #efefef, #fafafa);
            filter: progid:dximagetransform.microsoft.gradient(startColorStr='#e3e3e3', EndColorStr='#ffffff');
            -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorStr='#fafafa',EndColorStr='#efefef')";
            box-shadow: inset 0px 1px 1px white;
        }

        .left-menu .menu-body .static-menu a:hover {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }

        .left-menu .menu-body .static-menu a.active {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }
    </style>
</head>
<body>

<div class="pg-header">
    <div class="nav">
        <div class="logo-area left">
            <a href="#">
                <img class="logo" src="{% static 'imgs/logo.svg' %}">
                <span style="font-size: 18px;">资产统计 </span>
            </a>
        </div>

{#        <div class="left-menu left">#}
{#            <a class="menu-item">资产管理</a>#}
{#            <a class="menu-item">用户信息</a>#}
{#            <a class="menu-item">路飞管理</a>#}
{#            <div class="menu-item">#}
{#                <span>使用说明</span>#}
{#                <i class="fa fa-caret-down" aria-hidden="true"></i>#}
{#                <div class="more-info">#}
{#                    <a href="#" class="more-item">管他什么菜单</a>#}
{#                    <a href="#" class="more-item">实在是编不了</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}

        <div class="right-menu right clearfix">

            <div class="user-info right">
                <a href="#" class="avatar">
                    <img class="img-circle" src="{% static 'imgs/default.png' %}">
                </a>

                <div class="more-info">
                    <a href="#" class="more-item">个人信息</a>
                    <a href="/logout/" class="more-item">注销</a>
                </div>
            </div>

            <a class="user-menu right">
                消息
                <i class="fa fa-commenting-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                通知
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                任务
                <i class="fa fa-bell-o" aria-hidden="true"></i>
                <span class="badge bg-danger">4</span>
            </a>
        </div>

    </div>
</div>
<div class="pg-body">
    <div class="left-menu">
        <div class="menu-body">
            <div class="static-menu">
{#                {% load ooxx %}#}
{#                {% show_menu request %}#}
{#                                <a href="/user/list/" class="active">#}
{#                                    <span class="icon-wrap"><i class="fa fa-connectdevelop"></i></span> 用户管理</a>#}
                                <a href="/asset/list/">
                                    <span class="icon-wrap"><i class="fa fa-code-fork"></i></span> 资产管理</a>
            </div>

        </div>
    </div>
    <div class="right-body">
        <div>
            <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">

{#                <li><a href="#">首页</a></li>#}
{#                <li class="active">客户管理</li>#}

            </ol>
        </div>
        {% block content %} {% endblock %}
    </div>
</div>


<script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %} "></script>
{% block js %} {% endblock %}
</body>
</html>

hnf/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
{#        <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">#}
    <link rel="stylesheet" href="/static/css/login.css">
</head>

<body>
<div class="main">
    <div class="login">
        <h1>资产统计系统</h1>
        <div class="inset login-box">
            <!--start-main-->
            <form action="" method="post">
                {% csrf_token %}

                <div>
                    <h2>管理登录</h2>
                    <span><label>用户名</label></span>
                    <input type="text" name="username" class="textbox" placeholder="请输入用户名">
                </div>
                <div>
                    <span><label>密码</label></span>
                    <span><input type="password" name="password" class="password" placeholder="请输入密码"></span>

                </div>
                <div class="sign">
                        <p>
                            <input type="submit" value="登录" class="submit">

                        </p>
                     <p class="login-error" style="color: red">{{ error_msg }}</p>

                </div>
            </form>
        </div>
    </div>
    <!--//end-main-->
</div>

<div class="copy-right">
    <p>&copy; 2018 Ethos Login Form. All Rights Reserved</p>

</div>
{% load static %}

<script src="../static/js/jquery-3.3.1.min.js"></script>
<script src="{% static 'js/login.js' %}"></script>
</body>
</html>

hnf/templates/result.html
{% extends 'layout.html' %}

{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
            <a class="btn btn-default" href="/asset/add/">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加资产
            </a>
            <a class="btn btn-default" href="/asset/import/">
                <i class="fa fa-file-excel-o" aria-hidden="true"></i> 批量导入
            </a>
            <div class="right" style="margin-left: 911px" >
                <form method="get" action="{% url 'search' %}">
{#                  {% csrf_token %}#}
                  <input name="q"  type="search" placeholder="请输入姓名" required>
                  <button type="submit">搜索</button>
                </form>

            </div>

        </div>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>品牌</th>
                <th>型号</th>
                <th>编号</th>
                <th>领用时间</th>
                <th>领用人</th>
                <th>归还时间</th>
                <th>备注</th>
                <th>编辑</th>

            </tr>
            </thead>
            <tbody>
            {% if error_msg %}
                <p>{{ error_msg }}</p>
            {% endif %}
            {% for row in post_list %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.brand }}</td>
                    <td>{{ row.model }}</td>
                    <td>{{ row.number }}</td>
                    <td>{{ row.leader_time|date:"Y-m-d" }}</td>
                    <td>{{ row.leader }}</td>
                    <td>{{ row.return_time|date:"Y-m-d" }}</td>
                    <td>{{ row.other }}</td>

                    <td>
                        <a style="color: #333333;" href="/asset/edit/{{ row.id }}/">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        |
                        <a style="color: #d9534f;" href="/asset/del/{{ row.id }}/"><i class="fa fa-trash-o"></i></a>
                    </td>

                </tr>
                {% empty %}
                    <div class="no-post">
                        <span class="font-16" style="color: red" >没有搜索到符合条件的人员</span>
                    </div>
            {% endfor %}
            </tbody>
        </table>
    {{ page_html|safe }}
    </div>
{% endblock %}